interface Country {
  label: {
    fr: string;
    en: string;
    jp: string;
  };
  value: string;
}
export const countriesList: Country[] = [
  { label: { fr: 'France', en: 'France', jp: 'フランス' }, value: 'FR' },
  { label: { fr: 'Afghanistan', en: 'Afghanistan', jp: 'アフガニスタン' }, value: 'AF' },
  { label: { fr: 'Afrique du Sud', en: 'South Africa', jp: '南アフリカ' }, value: 'ZA' },
  { label: { fr: 'Åland, Îles', en: 'Åland Islands', jp: 'オーランド諸島' }, value: 'AX' },
  { label: { fr: 'Albanie', en: 'Albania', jp: 'アルバニア' }, value: 'AL' },
  { label: { fr: 'Algérie', en: 'Algeria', jp: 'アルジェリア' }, value: 'DZ' },
  { label: { fr: 'Allemagne', en: 'Germany', jp: 'ドイツ' }, value: 'DE' },
  { label: { fr: 'Andorre', en: 'Andorra', jp: 'アンドラ' }, value: 'AD' },
  { label: { fr: 'Angola', en: 'Angola', jp: 'アンゴラ' }, value: 'AO' },
  { label: { fr: 'Anguilla', en: 'Anguilla', jp: 'アンギラ' }, value: 'AI' },
  { label: { fr: 'Antarctique', en: 'Antarctica', jp: '南極' }, value: 'AQ' },
  { label: { fr: 'Antigua et Barbuda', en: 'Antigua and Barbuda', jp: 'アンティグア・バーブーダ' }, value: 'AG' },
  { label: { fr: 'Arabie Saoudite', en: 'Saudi Arabia', jp: 'サウジアラビア' }, value: 'SA' },
  { label: { fr: 'Argentine', en: 'Argentina', jp: 'アルゼンチン' }, value: 'AR' },
  { label: { fr: 'Arménie', en: 'Armenia', jp: 'アルメニア' }, value: 'AM' },
  { label: { fr: 'Aruba', en: 'Aruba', jp: 'アルバ' }, value: 'AW' },
  { label: { fr: 'Australie', en: 'Australia', jp: 'オーストラリア' }, value: 'AU' },
  { label: { fr: 'Autriche', en: 'Austria', jp: 'オーストリア' }, value: 'AT' },
  { label: { fr: 'Azerbaïdjan', en: 'Azerbaijan', jp: 'アゼルバイジャン' }, value: 'AZ' },
  { label: { fr: 'Bahamas', en: 'Bahamas', jp: 'バハマ' }, value: 'BS' },
  { label: { fr: 'Bahreïn', en: 'Bahrain', jp: 'バーレーン' }, value: 'BH' },
  { label: { fr: 'Bangladesh', en: 'Bangladesh', jp: 'バングラデシュ' }, value: 'BD' },
  { label: { fr: 'Barbade', en: 'Barbados', jp: 'バルバドス' }, value: 'BB' },
  { label: { fr: 'Bélarus', en: 'Belarus', jp: 'ベラルーシ' }, value: 'BY' },
  { label: { fr: 'Belgique', en: 'Belgium', jp: 'ベルギー' }, value: 'BE' },
  { label: { fr: 'Belize', en: 'Belize', jp: 'ベリーズ' }, value: 'BZ' },
  { label: { fr: 'Bénin', en: 'Benin', jp: 'ベナン' }, value: 'BJ' },
  { label: { fr: 'Bermudes', en: 'Bermuda', jp: 'バミューダ' }, value: 'BM' },
  { label: { fr: 'Bhoutan', en: 'Bhutan', jp: 'ブータン' }, value: 'BT' },
  { label: { fr: 'Bolivie', en: 'Bolivia', jp: 'ボリビア' }, value: 'BO' },
  { label: { fr: 'Bonaire, Saint Eustache et Saba', en: 'Bonaire, Saint Eustatius and Saba', jp: 'ボネール、シント・ユースタティウスおよびサバ' }, value: 'BQ' },
  { label: { fr: 'Bosnie Herzégovine', en: 'Bosnia and Herzegovina', jp: 'ボスニア・ヘルツェゴビナ' }, value: 'BA' },
  { label: { fr: 'Botswana', en: 'Botswana', jp: 'ボツワナ' }, value: 'BW' },
  { label: { fr: 'Bouvet, Île', en: 'Bouvet Island', jp: 'ブーベ島' }, value: 'BV' },
  { label: { fr: 'Brésil', en: 'Brazil', jp: 'ブラジル' }, value: 'BR' },
  { label: { fr: 'Brunei Darussalam', en: 'Brunei Darussalam', jp: 'ブルネイ' }, value: 'BN' },
  { label: { fr: 'Bulgarie', en: 'Bulgaria', jp: 'ブルガリア' }, value: 'BG' },
  { label: { fr: 'Burkina Faso', en: 'Burkina Faso', jp: 'ブルキナファソ' }, value: 'BF' },
  { label: { fr: 'Burundi', en: 'Burundi', jp: 'ブルンジ' }, value: 'BI' },
  { label: { fr: 'Caïmans, Îles', en: 'Cayman Islands', jp: 'ケイマン諸島' }, value: 'KY' },
  { label: { fr: 'Cambodge', en: 'Cambodia', jp: 'カンボジア' }, value: 'KH' },
  { label: { fr: 'Cameroun', en: 'Cameroon', jp: 'カメルーン' }, value: 'CM' },
  { label: { fr: 'Canada', en: 'Canada', jp: 'カナダ' }, value: 'CA' },
  { label: { fr: 'Cap Vert', en: 'Cape Verde', jp: 'カーボベルデ' }, value: 'CV' },
  { label: { fr: 'Centrafricaine, République', en: 'Central African Republic', jp: '中央アフリカ共和国' }, value: 'CF' },
  { label: { fr: 'Chili', en: 'Chile', jp: 'チリ' }, value: 'CL' },
  { label: { fr: 'Chine', en: 'China', jp: '中国' }, value: 'CN' },
  { label: { fr: 'Christmas, Île', en: 'Christmas Island', jp: 'クリスマス島' }, value: 'CX' },
  { label: { fr: 'Chypre', en: 'Cyprus', jp: 'キプロス' }, value: 'CY' },
  { label: { fr: 'Cocos (Keeling), Îles', en: 'Cocos (Keeling) Islands', jp: 'ココス（キーリング）諸島' }, value: 'CC' },
  { label: { fr: 'Colombie', en: 'Colombia', jp: 'コロンビア' }, value: 'CO' },
  { label: { fr: 'Comores', en: 'Comoros', jp: 'コモロ' }, value: 'KM' },
  { label: { fr: 'Congo', en: 'Congo', jp: 'コンゴ共和国' }, value: 'CG' },
  { label: { fr: 'Congo, la République Démocratique du', en: 'Democratic Republic of the Congo', jp: 'コンゴ民主共和国' }, value: 'CD' },
  { label: { fr: 'Cook, Îles', en: 'Cook Islands', jp: 'クック諸島' }, value: 'CK' },
  { label: { fr: 'Corée du Sud', en: 'South Korea', jp: '大韓民国' }, value: 'KR' },
  { label: { fr: 'Corée du Nord', en: 'North Korea', jp: '朝鮮民主主義人民共和国' }, value: 'KP' },
  { label: { fr: 'Costa Rica', en: 'Costa Rica', jp: 'コスタリカ' }, value: 'CR' },
  { label: { fr: 'Côte d\'Ivoire', en: 'Côte d\'Ivoire', jp: 'コートジボワール' }, value: 'CI' },
  { label: { fr: 'Croatie', en: 'Croatia', jp: 'クロアチア' }, value: 'HR' },
  { label: { fr: 'Cuba', en: 'Cuba', jp: 'キューバ' }, value: 'CU' },
  { label: { fr: 'Curaçao', en: 'Curaçao', jp: 'キュラソー' }, value: 'CW' },
  { label: { fr: 'Danemark', en: 'Denmark', jp: 'デンマーク' }, value: 'DK' },
  { label: { fr: 'Djibouti', en: 'Djibouti', jp: 'ジブチ' }, value: 'DJ' },
  { label: { fr: 'Dominicaine, République', en: 'Dominican Republic', jp: 'ドミニカ共和国' }, value: 'DO' },
  { label: { fr: 'Dominique', en: 'Dominica', jp: 'ドミニカ' }, value: 'DM' },
  { label: { fr: 'Égypte', en: 'Egypt', jp: 'エジプト' }, value: 'EG' },
  { label: { fr: 'El Salvador', en: 'El Salvador', jp: 'エルサルバドル' }, value: 'SV' },
  { label: { fr: 'Émirats Arabes Unis', en: 'United Arab Emirates', jp: 'アラブ首長国連邦' }, value: 'AE' },
  { label: { fr: 'Équateur', en: 'Ecuador', jp: 'エクアドル' }, value: 'EC' },
  { label: { fr: 'Érythrée', en: 'Eritrea', jp: 'エリトリア' }, value: 'ER' },
  { label: { fr: 'Espagne', en: 'Spain', jp: 'スペイン' }, value: 'ES' },
  { label: { fr: 'Estonie', en: 'Estonia', jp: 'エストニア' }, value: 'EE' },
  { label: { fr: 'Eswatini', en: 'Eswatini', jp: 'エスワティニ' }, value: 'SZ' },
  { label: { fr: 'États Fédérés de Micronésie', en: 'Federated States of Micronesia', jp: 'ミクロネシア連邦' }, value: 'FM' },
  { label: { fr: 'États-Unis', en: 'United States of America', jp: 'アメリカ合衆国' }, value: 'US' },
  { label: { fr: 'Éthiopie', en: 'Ethiopia', jp: 'エチオピア' }, value: 'ET' },
  { label: { fr: 'Falkland, Îles (Malvinas)', en: 'Falkland Islands (Malvinas)', jp: 'フォークランド諸島（マルビナス諸島）' }, value: 'FK' },
  { label: { fr: 'Fidji', en: 'Fiji', jp: 'フィジー' }, value: 'FJ' },
  { label: { fr: 'Finlande', en: 'Finland', jp: 'フィンランド' }, value: 'FI' },
  { label: { fr: 'Gabon', en: 'Gabon', jp: 'ガボン' }, value: 'GA' },
  { label: { fr: 'Gambie', en: 'Gambia', jp: 'ガンビア' }, value: 'GM' },
  { label: { fr: 'Géorgie', en: 'Georgia', jp: 'ジョージア' }, value: 'GE' },
  { label: { fr: 'Ghana', en: 'Ghana', jp: 'ガーナ' }, value: 'GH' },
  { label: { fr: 'Gibraltar', en: 'Gibraltar', jp: 'ジブラルタル' }, value: 'GI' },
  { label: { fr: 'Grèce', en: 'Greece', jp: 'ギリシャ' }, value: 'GR' },
  { label: { fr: 'Grenade', en: 'Grenada', jp: 'グレナダ' }, value: 'GD' },
  { label: { fr: 'Groenland', en: 'Greenland', jp: 'グリーンランド' }, value: 'GL' },
  { label: { fr: 'Guadeloupe', en: 'Guadeloupe', jp: 'グアドループ' }, value: 'GP' },
  { label: { fr: 'Guam', en: 'Guam', jp: 'グアム' }, value: 'GU' },
  { label: { fr: 'Guatemala', en: 'Guatemala', jp: 'グアテマラ' }, value: 'GT' },
  { label: { fr: 'Guernesey', en: 'Guernsey', jp: 'ガーンジー' }, value: 'GG' },
  { label: { fr: 'Guinée', en: 'Guinea', jp: 'ギニア' }, value: 'GN' },
  { label: { fr: 'Guinée-Bissau', en: 'Guinea-Bissau', jp: 'ギニアビサウ' }, value: 'GW' },
  { label: { fr: 'Guinée équatoriale', en: 'Equatorial Guinea', jp: '赤道ギニア' }, value: 'GQ' },
  { label: { fr: 'Guyana', en: 'Guyana', jp: 'ガイアナ' }, value: 'GY' },
  { label: { fr: 'Guyane', en: 'French Guiana', jp: 'フランス領ギアナ' }, value: 'GF' },
  { label: { fr: 'Haïti', en: 'Haiti', jp: 'ハイチ' }, value: 'HT' },
  { label: { fr: 'Heard et McDonald, Îles', en: 'Heard Island and McDonald Islands', jp: 'ハード島とマクドナルド諸島' }, value: 'HM' },
  { label: { fr: 'Honduras', en: 'Honduras', jp: 'ホンジュラス' }, value: 'HN' },
  { label: { fr: 'Hong-Kong', en: 'Hong Kong', jp: '香港' }, value: 'HK' },
  { label: { fr: 'Hongrie', en: 'Hungary', jp: 'ハンガリー' }, value: 'HU' },
  { label: { fr: 'Inde', en: 'India', jp: 'インド' }, value: 'IN' },
  { label: { fr: 'Indonésie', en: 'Indonesia', jp: 'インドネシア' }, value: 'ID' },
  { label: { fr: 'Iran', en: 'Iran', jp: 'イラン・イスラム共和国' }, value: 'IR' },
  { label: { fr: 'Iraq', en: 'Iraq', jp: 'イラク' }, value: 'IQ' },
  { label: { fr: 'Irlande', en: 'Ireland', jp: 'アイルランド' }, value: 'IE' },
  { label: { fr: 'Islande', en: 'Iceland', jp: 'アイスランド' }, value: 'IS' },
  { label: { fr: 'Israël', en: 'Israel', jp: 'イスラエル' }, value: 'IL' },
  { label: { fr: 'Italie', en: 'Italy', jp: 'イタリア' }, value: 'IT' },
  { label: { fr: 'Jamaïque', en: 'Jamaica', jp: 'ジャマイカ' }, value: 'JM' },
  { label: { fr: 'Japon', en: 'Japan', jp: '日本' }, value: 'JP' },
  { label: { fr: 'Jersey', en: 'Jersey', jp: 'ジャージー' }, value: 'JE' },
  { label: { fr: 'Jordanie', en: 'Jordan', jp: 'ヨルダン' }, value: 'JO' },
  { label: { fr: 'Kazakhstan', en: 'Kazakhstan', jp: 'カザフスタン' }, value: 'KZ' },
  { label: { fr: 'Kenya', en: 'Kenya', jp: 'ケニア' }, value: 'KE' },
  { label: { fr: 'Kirghizistan', en: 'Kyrgyzstan', jp: 'キルギス' }, value: 'KG' },
  { label: { fr: 'Kiribati', en: 'Kiribati', jp: 'キリバス' }, value: 'KI' },
  { label: { fr: 'Koweït', en: 'Kuwait', jp: 'クウェート' }, value: 'KW' },
  { label: { fr: 'Lesotho', en: 'Lesotho', jp: 'レソト' }, value: 'LS' },
  { label: { fr: 'Lettonie', en: 'Latvia', jp: 'ラトビア' }, value: 'LV' },
  { label: { fr: 'Liban', en: 'Lebanon', jp: 'レバノン' }, value: 'LB' },
  { label: { fr: 'Libéria', en: 'Liberia', jp: 'リベリア' }, value: 'LR' },
  { label: { fr: 'Libye', en: 'Libya', jp: 'リビア' }, value: 'LY' },
  { label: { fr: 'Liechtenstein', en: 'Liechtenstein', jp: 'リヒテンシュタイン' }, value: 'LI' },
  { label: { fr: 'Lituanie', en: 'Lithuania', jp: 'リトアニア' }, value: 'LT' },
  { label: { fr: 'Luxembourg', en: 'Luxembourg', jp: 'ルクセンブルク' }, value: 'LU' },
  { label: { fr: 'Macao', en: 'Macao', jp: 'マカオ' }, value: 'MO' },
  { label: { fr: 'Macédoine du Nord', en: 'North Macedonia', jp: '北マケドニア' }, value: 'MK' },
  { label: { fr: 'Madagascar', en: 'Madagascar', jp: 'マダガスカル' }, value: 'MG' },
  { label: { fr: 'Malaisie', en: 'Malaysia', jp: 'マレーシア' }, value: 'MY' },
  { label: { fr: 'Malawi', en: 'Malawi', jp: 'マラウイ' }, value: 'MW' },
  { label: { fr: 'Maldives', en: 'Maldives', jp: 'モルディブ' }, value: 'MV' },
  { label: { fr: 'Mali', en: 'Mali', jp: 'マリ' }, value: 'ML' },
  { label: { fr: 'Malouines, Îles (Falkland)', en: 'Falkland Islands (Malvinas)', jp: 'フォークランド諸島（マルビナス諸島）' }, value: 'FK' },
  { label: { fr: 'Malte', en: 'Malta', jp: 'マルタ' }, value: 'MT' },
  { label: { fr: 'Mariannes du Nord, Îles', en: 'Northern Mariana Islands', jp: '北マリアナ諸島' }, value: 'MP' },
  { label: { fr: 'Maroc', en: 'Morocco', jp: 'モロッコ' }, value: 'MA' },
  { label: { fr: 'Marshall, Îles', en: 'Marshall Islands', jp: 'マーシャル諸島' }, value: 'MH' },
  { label: { fr: 'Martinique', en: 'Martinique', jp: 'マルティニーク' }, value: 'MQ' },
  { label: { fr: 'Maurice', en: 'Mauritius', jp: 'モーリシャス' }, value: 'MU' },
  { label: { fr: 'Mauritanie', en: 'Mauritania', jp: 'モーリタニア' }, value: 'MR' },
  { label: { fr: 'Mayotte', en: 'Mayotte', jp: 'マヨット' }, value: 'YT' },
  { label: { fr: 'Mexique', en: 'Mexico', jp: 'メキシコ' }, value: 'MX' },
  { label: { fr: 'Moldova, République de', en: 'Moldova', jp: 'モルドバ共和国' }, value: 'MD' },
  { label: { fr: 'Monaco', en: 'Monaco', jp: 'モナコ' }, value: 'MC' },
  { label: { fr: 'Mongolie', en: 'Mongolia', jp: 'モンゴル' }, value: 'MN' },
  { label: { fr: 'Monténégro', en: 'Montenegro', jp: 'モンテネグロ' }, value: 'ME' },
  { label: { fr: 'Montserrat', en: 'Montserrat', jp: 'モントセラト' }, value: 'MS' },
  { label: { fr: 'Mozambique', en: 'Mozambique', jp: 'モザンビーク' }, value: 'MZ' },
  { label: { fr: 'Myanmar', en: 'Myanmar', jp: 'ミャンマー' }, value: 'MM' },
  { label: { fr: 'Namibie', en: 'Namibia', jp: 'ナミビア' }, value: 'NA' },
  { label: { fr: 'Nauru', en: 'Nauru', jp: 'ナウル' }, value: 'NR' },
  { label: { fr: 'Népal', en: 'Nepal', jp: 'ネパール' }, value: 'NP' },
  { label: { fr: 'Nicaragua', en: 'Nicaragua', jp: 'ニカラグア' }, value: 'NI' },
  { label: { fr: 'Niger', en: 'Niger', jp: 'ニジェール' }, value: 'NE' },
  { label: { fr: 'Nigéria', en: 'Nigeria', jp: 'ナイジェリア' }, value: 'NG' },
  { label: { fr: 'Niue', en: 'Niue', jp: 'ニウエ' }, value: 'NU' },
  { label: { fr: 'Norfolk, Île', en: 'Norfolk Island', jp: 'ノーフォーク島' }, value: 'NF' },
  { label: { fr: 'Norvège', en: 'Norway', jp: 'ノルウェー' }, value: 'NO' },
  { label: { fr: 'Nouvelle-Calédonie', en: 'New Caledonia', jp: 'ニューカレドニア' }, value: 'NC' },
  { label: { fr: 'Nouvelle-Zélande', en: 'New Zealand', jp: 'ニュージーランド' }, value: 'NZ' },
  { label: { fr: 'Oman', en: 'Oman', jp: 'オマーン' }, value: 'OM' },
  { label: { fr: 'Ouganda', en: 'Uganda', jp: 'ウガンダ' }, value: 'UG' },
  { label: { fr: 'Ouzbékistan', en: 'Uzbekistan', jp: 'ウズベキスタン' }, value: 'UZ' },
  { label: { fr: 'Pakistan', en: 'Pakistan', jp: 'パキスタン' }, value: 'PK' },
  { label: { fr: 'Palaos', en: 'Palau', jp: 'パラオ' }, value: 'PW' },
  { label: { fr: 'Palestine, État de', en: 'Palestine, State of', jp: 'パレスチナ国' }, value: 'PS' },
  { label: { fr: 'Panama', en: 'Panama', jp: 'パナマ' }, value: 'PA' },
  { label: { fr: 'Papouasie-Nouvelle-Guinée', en: 'Papua New Guinea', jp: 'パプアニューギニア' }, value: 'PG' },
  { label: { fr: 'Paraguay', en: 'Paraguay', jp: 'パラグアイ' }, value: 'PY' },
  { label: { fr: 'Pays-Bas', en: 'Netherlands', jp: 'オランダ' }, value: 'NL' },
  { label: { fr: 'Pérou', en: 'Peru', jp: 'ペルー' }, value: 'PE' },
  { label: { fr: 'Philippines', en: 'Philippines', jp: 'フィリピン' }, value: 'PH' },
  { label: { fr: 'Pitcairn', en: 'Pitcairn', jp: 'ピトケアン' }, value: 'PN' },
  { label: { fr: 'Pologne', en: 'Poland', jp: 'ポーランド' }, value: 'PL' },
  { label: { fr: 'Polynésie française', en: 'French Polynesia', jp: 'フランス領ポリネシア' }, value: 'PF' },
  { label: { fr: 'Porto Rico', en: 'Puerto Rico', jp: 'プエルトリコ' }, value: 'PR' },
  { label: { fr: 'Portugal', en: 'Portugal', jp: 'ポルトガル' }, value: 'PT' },
  { label: { fr: 'Qatar', en: 'Qatar', jp: 'カタール' }, value: 'QA' },
  { label: { fr: 'Réunion', en: 'Reunion', jp: 'レユニオン' }, value: 'RE' },
  { label: { fr: 'Roumanie', en: 'Romania', jp: 'ルーマニア' }, value: 'RO' },
  { label: { fr: 'Royaume-Uni', en: 'United Kingdom', jp: 'イギリス' }, value: 'GB' },
  { label: { fr: 'Russie', en: 'Russia', jp: 'ロシア' }, value: 'RU' },
  { label: { fr: 'Rwanda', en: 'Rwanda', jp: 'ルワンダ' }, value: 'RW' },
  { label: { fr: 'Sahara Occidental', en: 'Western Sahara', jp: '西サハラ' }, value: 'EH' },
  { label: { fr: 'Saint-Barthélemy', en: 'Saint Barthélemy', jp: 'サン・バルテルミー' }, value: 'BL' },
  { label: { fr: 'Sainte-Hélène', en: 'Saint Helena', jp: 'セントヘレナ' }, value: 'SH' },
  { label: { fr: 'Sainte-Lucie', en: 'Saint Lucia', jp: 'セントルシア' }, value: 'LC' },
  { label: { fr: 'Saint-Kitts-et-Nevis', en: 'Saint Kitts and Nevis', jp: 'セントクリストファー・ネイビス' }, value: 'KN' },
  { label: { fr: 'Saint-Marin', en: 'San Marino', jp: 'サンマリノ' }, value: 'SM' },
  { label: { fr: 'Saint-Martin (partie française)', en: 'Saint Martin (French Part)', jp: 'サン・マルタン島（フランス領）' }, value: 'MF' },
  { label: { fr: 'Saint-Martin (partie néerlandaise)', en: 'Sint Maarten (Dutch part)', jp: 'シント・マールテン島（オランダ領）' }, value: 'SX' },
  { label: { fr: 'Saint-Pierre-et-Miquelon', en: 'Saint Pierre and Miquelon', jp: 'サンピエール島・ミクロン島' }, value: 'PM' },
  { label: { fr: 'Saint-Vincent-et-les-Grenadines', en: 'Saint Vincent and the Grenadines', jp: 'セントビンセント・グレナディーン' }, value: 'VC' },
  { label: { fr: 'Samoa', en: 'Samoa', jp: 'サモア' }, value: 'WS' },
  { label: { fr: 'Samoa américaines', en: 'American Samoa', jp: 'アメリカ領サモア' }, value: 'AS' },
  { label: { fr: 'Sao Tomé-et-Principe', en: 'Sao Tome and Principe', jp: 'サントメ・プリンシペ' }, value: 'ST' },
  { label: { fr: 'Sénégal', en: 'Senegal', jp: 'セネガル' }, value: 'SN' },
  { label: { fr: 'Serbie', en: 'Serbia', jp: 'セルビア' }, value: 'RS' },
  { label: { fr: 'Seychelles', en: 'Seychelles', jp: 'セーシェル' }, value: 'SC' },
  { label: { fr: 'Sierra Leone', en: 'Sierra Leone', jp: 'シエラレオネ' }, value: 'SL' },
  { label: { fr: 'Singapour', en: 'Singapore', jp: 'シンガポール' }, value: 'SG' },
  { label: { fr: 'Slovaquie', en: 'Slovakia', jp: 'スロバキア' }, value: 'SK' },
  { label: { fr: 'Slovénie', en: 'Slovenia', jp: 'スロベニア' }, value: 'SI' },
  { label: { fr: 'Somalie', en: 'Somalia', jp: 'ソマリア' }, value: 'SO' },
  { label: { fr: 'Soudan', en: 'Sudan', jp: 'スーダン' }, value: 'SD' },
  { label: { fr: 'Soudan du Sud', en: 'South Sudan', jp: '南スーダン' }, value: 'SS' },
  { label: { fr: 'Sri Lanka', en: 'Sri Lanka', jp: 'スリランカ' }, value: 'LK' },
  { label: { fr: 'Suède', en: 'Sweden', jp: 'スウェーデン' }, value: 'SE' },
  { label: { fr: 'Suisse', en: 'Switzerland', jp: 'スイス' }, value: 'CH' },
  { label: { fr: 'Suriname', en: 'Suriname', jp: 'スリナム' }, value: 'SR' },
  { label: { fr: 'Svalbard et île Jan Mayen', en: 'Svalbard and Jan Mayen', jp: 'スバールバル諸島およびヤンマイエン島' }, value: 'SJ' },
  { label: { fr: 'Syrienne, République arabe', en: 'Syrian Arab Republic', jp: 'シリア・アラブ共和国' }, value: 'SY' },
  { label: { fr: 'Tadjikistan', en: 'Tajikistan', jp: 'タジキスタン' }, value: 'TJ' },
  { label: { fr: 'Tanzanie, République-Unie de', en: 'Tanzania, United Republic of', jp: 'タンザニア連合共和国' }, value: 'TZ' },
  { label: { fr: 'Tchad', en: 'Chad', jp: 'チャド' }, value: 'TD' },
  { label: { fr: 'Tchéquie', en: 'Czech Republic', jp: 'チェコ共和国' }, value: 'CZ' },
  { label: { fr: 'Terres australes françaises', en: 'French Southern Territories', jp: 'フランス領南方・南極地域' }, value: 'TF' },
  { label: { fr: 'Thaïlande', en: 'Thailand', jp: 'タイ' }, value: 'TH' },
  { label: { fr: 'Timor-Leste', en: 'Timor-Leste', jp: '東ティモール' }, value: 'TL' },
  { label: { fr: 'Togo', en: 'Togo', jp: 'トーゴ' }, value: 'TG' },
  { label: { fr: 'Tokélaou', en: 'Tokelau', jp: 'トケラウ' }, value: 'TK' },
  { label: { fr: 'Tonga', en: 'Tonga', jp: 'トンガ' }, value: 'TO' },
  { label: { fr: 'Trinité-et-Tobago', en: 'Trinidad and Tobago', jp: 'トリニダード・トバゴ' }, value: 'TT' },
  { label: { fr: 'Tristan da Cunha', en: 'Tristan da Cunha', jp: 'トリスタンダクーニャ' }, value: 'TA' },
  { label: { fr: 'Tunisie', en: 'Tunisia', jp: 'チュニジア' }, value: 'TN' },
  { label: { fr: 'Turkménistan', en: 'Turkmenistan', jp: 'トルクメニスタン' }, value: 'TM' },
  { label: { fr: 'Turquie', en: 'Turkey', jp: 'トルコ' }, value: 'TR' },
  { label: { fr: 'Tuvalu', en: 'Tuvalu', jp: 'ツバル' }, value: 'TV' },
  { label: { fr: 'Ukraine', en: 'Ukraine', jp: 'ウクライナ' }, value: 'UA' },
  { label: { fr: 'Uruguay', en: 'Uruguay', jp: 'ウルグアイ' }, value: 'UY' },
  { label: { fr: 'Vanuatu', en: 'Vanuatu', jp: 'バヌアツ' }, value: 'VU' },
  { label: { fr: 'Vatican', en: 'Vatican', jp: 'バチカン' }, value: 'VA' },
  { label: { fr: 'Vénézuela', en: 'Venezuela', jp: 'ベネズエラ' }, value: 'VE' },
  { label: { fr: 'Vierges britanniques, Îles', en: 'Virgin Islands (British)', jp: 'イギリス領ヴァージン諸島' }, value: 'VG' },
  { label: { fr: 'Vierges des États-Unis, Îles', en: 'Virgin Islands (U.S.)', jp: 'アメリカ領ヴァージン諸島' }, value: 'VI' },
  { label: { fr: 'Vietnam', en: 'Vietnam', jp: 'ベトナム' }, value: 'VN' },
  { label: { fr: 'Wallis-et-Futuna', en: 'Wallis and Futuna', jp: 'ウォリス・フツナ' }, value: 'WF' },
  { label: { fr: 'Yémen', en: 'Yemen', jp: 'イエメン' }, value: 'YE' },
  { label: { fr: 'Zambie', en: 'Zambia', jp: 'ザンビア' }, value: 'ZM' },
  { label: { fr: 'Zimbabwe', en: 'Zimbabwe', jp: 'ジンバブエ' }, value: 'ZW' },
  { label: { fr: 'Åland, Îles', en: 'Åland Islands', jp: 'オーランド諸島' }, value: 'AX' }
]

// export const countriesValues = countriesList.map((country: Country, locale: [keyof typeof country['label']]) => {
//   const label = country.label[locale];
//   const value = country.value;
//   return { label, value };
// });

export default countriesList;
