
export const countries = [
  { label: 'France', value: 'FR' },
  { label: 'Afghanistan', value: 'AF' },
  { label: 'Afrique du sud', value: 'ZA' },
  { label: 'Åland, îles', value: 'AX' },
  { label: 'Albanie', value: 'AL' },
  { label: 'Algérie', value: 'DZ' },
  { label: 'Allemagne', value: 'DE' },
  { label: 'Andorre', value: 'AD' },
  { label: 'Angola', value: 'AO' },
  { label: 'Anguilla', value: 'AI' },
  { label: 'Antarctique', value: 'AQ' },
  { label: 'Antigua et barbuda', value: 'AG' },
  { label: 'Arabie saoudite', value: 'SA' },
  { label: 'Argentine', value: 'AR' },
  { label: 'Arménie', value: 'AM' },
  { label: 'Aruba', value: 'AW' },
  { label: 'Australie', value: 'AU' },
  { label: 'Autriche', value: 'AT' },
  { label: 'Azerbaïdjan', value: 'AZ' },
  { label: 'Bahamas', value: 'BS' },
  { label: 'Bahreïn', value: 'BH' },
  { label: 'Bangladesh', value: 'BD' },
  { label: 'Barbade', value: 'BB' },
  { label: 'Bélarus', value: 'BY' },
  { label: 'Belgique', value: 'BE' },
  { label: 'Belize', value: 'BZ' },
  { label: 'Bénin', value: 'BJ' },
  { label: 'Bermudes', value: 'BM' },
  { label: 'Bhoutan', value: 'BT' },
  { label: 'Bolivie', value: 'BO' },
  { label: 'Bonaire, saint eustache et saba', value: 'BQ' },
  { label: 'Bosnie herzégovine', value: 'BA' },
  { label: 'Botswana', value: 'BW' },
  { label: 'Bouvet, île', value: 'BV' },
  { label: 'Brésil', value: 'BR' },
  { label: 'Brunei darussalam', value: 'BN' },
  { label: 'Bulgarie', value: 'BG' },
  { label: 'Burkina faso', value: 'BF' },
  { label: 'Burundi', value: 'BI' },
  { label: 'Caïmans, îles', value: 'KY' },
  { label: 'Cambodge', value: 'KH' },
  { label: 'Cameroun', value: 'CM' },
  { label: 'Canada', value: 'CA' },
  { label: 'Cap vert', value: 'CV' },
  { label: 'Centrafricaine, république', value: 'CF' },
  { label: 'Chili', value: 'CL' },
  { label: 'Chine', value: 'CN' },
  { label: 'Christmas, île', value: 'CX' },
  { label: 'Chypre', value: 'CY' },
  { label: 'Cocos (keeling), îles', value: 'CC' },
  { label: 'Colombie', value: 'CO' },
  { label: 'Comores', value: 'KM' },
  { label: 'Congo', value: 'CG' },
  { label: 'Congo, la république démocratique du', value: 'CD' },
  { label: 'Cook, îles', value: 'CK' },
  { label: 'Corée, république de', value: 'KR' },
  { label: 'Corée, république populaire démocratique de', value: 'KP' },
  { label: 'Costa rica', value: 'CR' },
  { label: 'Côte d\'ivoire', value: 'CI' },
  { label: 'Croatie', value: 'HR' },
  { label: 'Cuba', value: 'CU' },
  { label: 'Curaçao', value: 'CW' },
  { label: 'Danemark', value: 'DK' },
  { label: 'Djibouti', value: 'DJ' },
  { label: 'Dominicaine, république', value: 'DO' },
  { label: 'Dominique', value: 'DM' },
  { label: 'Égypte', value: 'EG' },
  { label: 'El salvador', value: 'SV' },
  { label: 'Émirats arabes unis', value: 'AE' },
  { label: 'Équateur', value: 'EC' },
  { label: 'Érythrée', value: 'ER' },
  { label: 'Espagne', value: 'ES' },
  { label: 'Estonie', value: 'EE' },
  { label: 'États unis', value: 'US' },
  { label: 'Éthiopie', value: 'ET' },
  { label: 'Falkland, îles (malvinas)', value: 'FK' },
  { label: 'Féroé, îles', value: 'FO' },
  { label: 'Fidji', value: 'FJ' },
  { label: 'Finlande', value: 'FI' },
  { label: 'Gabon', value: 'GA' },
  { label: 'Gambie', value: 'GM' },
  { label: 'Géorgie', value: 'GE' },
  { label: 'Géorgie du sud et les îles sandwich du sud', value: 'GS' },
  { label: 'Ghana', value: 'GH' },
  { label: 'Gibraltar', value: 'GI' },
  { label: 'Grèce', value: 'GR' },
  { label: 'Grenade', value: 'GD' },
  { label: 'Groenland', value: 'GL' },
  { label: 'Guadeloupe', value: 'GP' },
  { label: 'Guam', value: 'GU' },
  { label: 'Guatemala', value: 'GT' },
  { label: 'Guernesey', value: 'GG' },
  { label: 'Guinée', value: 'GN' },
  { label: 'Guinée bissau', value: 'GW' },
  { label: 'Guinée équatoriale', value: 'GQ' },
  { label: 'Guyana', value: 'GY' },
  { label: 'Guyane française', value: 'GF' },
  { label: 'Haïti', value: 'HT' },
  { label: 'Heard et îles macdonald, île', value: 'HM' },
  { label: 'Honduras', value: 'HN' },
  { label: 'Hong kong', value: 'HK' },
  { label: 'Hongrie', value: 'HU' },
  { label: 'Île de man', value: 'IM' },
  { label: 'Îles mineures éloignées des états unis', value: 'UM' },
  { label: 'Îles vierges britanniques', value: 'VG' },
  { label: 'Îles vierges des états unis', value: 'VI' },
  { label: 'Inde', value: 'IN' },
  { label: 'Indonésie', value: 'ID' },
  { label: 'Iran, république islamique d\'', value: 'IR' },
  { label: 'Iraq', value: 'IQ' },
  { label: 'Irlande', value: 'IE' },
  { label: 'Islande', value: 'IS' },
  { label: 'Israël', value: 'IL' },
  { label: 'Italie', value: 'IT' },
  { label: 'Jamaïque', value: 'JM' },
  { label: 'Japon', value: 'JP' },
  { label: 'Jersey', value: 'JE' },
  { label: 'Jordanie', value: 'JO' },
  { label: 'Kazakhstan', value: 'KZ' },
  { label: 'Kenya', value: 'KE' },
  { label: 'Kirghizistan', value: 'KG' },
  { label: 'Kiribati', value: 'KI' },
  { label: 'Koweït', value: 'KW' },
  { label: 'Lao, république démocratique populaire', value: 'LA' },
  { label: 'Lesotho', value: 'LS' },
  { label: 'Lettonie', value: 'LV' },
  { label: 'Liban', value: 'LB' },
  { label: 'Libéria', value: 'LR' },
  { label: 'Libye', value: 'LY' },
  { label: 'Liechtenstein', value: 'LI' },
  { label: 'Lituanie', value: 'LT' },
  { label: 'Luxembourg', value: 'LU' },
  { label: 'Macao', value: 'MO' },
  { label: 'Macédoine, l\'ex république yougoslave de', value: 'MK' },
  { label: 'Madagascar', value: 'MG' },
  { label: 'Malaisie', value: 'MY' },
  { label: 'Malawi', value: 'MW' },
  { label: 'Maldives', value: 'MV' },
  { label: 'Mali', value: 'ML' },
  { label: 'Malte', value: 'MT' },
  { label: 'Mariannes du nord, îles', value: 'MP' },
  { label: 'Maroc', value: 'MA' },
  { label: 'Marshall, îles', value: 'MH' },
  { label: 'Martinique', value: 'MQ' },
  { label: 'Maurice', value: 'MU' },
  { label: 'Mauritanie', value: 'MR' },
  { label: 'Mayotte', value: 'YT' },
  { label: 'Mexique', value: 'MX' },
  { label: 'Micronésie, états fédérés de', value: 'FM' },
  { label: 'Moldova, république de', value: 'MD' },
  { label: 'Monaco', value: 'MC' },
  { label: 'Mongolie', value: 'MN' },
  { label: 'Monténégro', value: 'ME' },
  { label: 'Montserrat', value: 'MS' },
  { label: 'Mozambique', value: 'MZ' },
  { label: 'Myanmar', value: 'MM' },
  { label: 'Namibie', value: 'NA' },
  { label: 'Nauru', value: 'NR' },
  { label: 'Népal', value: 'NP' },
  { label: 'Nicaragua', value: 'NI' },
  { label: 'Niger', value: 'NE' },
  { label: 'Nigéria', value: 'NG' },
  { label: 'Niué', value: 'NU' },
  { label: 'Norfolk, île', value: 'NF' },
  { label: 'Norvège', value: 'NO' },
  { label: 'Nouvelle calédonie', value: 'NC' },
  { label: 'Nouvelle zélande', value: 'NZ' },
  { label: 'Océan indien, territoire britannique de l\'', value: 'IO' },
  { label: 'Oman', value: 'OM' },
  { label: 'Ouganda', value: 'UG' },
  { label: 'Ouzbékistan', value: 'UZ' },
  { label: 'Pakistan', value: 'PK' },
  { label: 'Palaos', value: 'PW' },
  { label: 'Palestinien occupé, territoire', value: 'PS' },
  { label: 'Panama', value: 'PA' },
  { label: 'Papouasie nouvelle guinée', value: 'PG' },
  { label: 'Paraguay', value: 'PY' },
  { label: 'Pays bas', value: 'NL' },
  { label: 'Pérou', value: 'PE' },
  { label: 'Philippines', value: 'PH' },
  { label: 'Pitcairn', value: 'PN' },
  { label: 'Pologne', value: 'PL' },
  { label: 'Polynésie française', value: 'PF' },
  { label: 'Porto rico', value: 'PR' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Qatar', value: 'QA' },
  { label: 'Réunion', value: 'RE' },
  { label: 'Roumanie', value: 'RO' },
  { label: 'Royaume uni', value: 'GB' },
  { label: 'Russie, fédération de', value: 'RU' },
  { label: 'Rwanda', value: 'RW' },
  { label: 'Sahara occidental', value: 'EH' },
  { label: 'Saint barthélemy', value: 'BL' },
  { label: 'Sainte hélène, ascension et tristan da cunha', value: 'SH' },
  { label: 'Sainte lucie', value: 'LC' },
  { label: 'Saint kitts et nevis', value: 'KN' },
  { label: 'Saint marin', value: 'SM' },
  { label: 'Saint martin(partie française)', value: 'MF' },
  { label: 'Saint martin (partie néerlandaise)', value: 'SX' },
  { label: 'Saint pierre et miquelon', value: 'PM' },
  { label: 'Saint siège (état de la cité du vatican)', value: 'VA' },
  { label: 'Saint vincent et les grenadines', value: 'VC' },
  { label: 'Salomon, îles', value: 'SB' },
  { label: 'Samoa', value: 'WS' },
  { label: 'Samoa américaines', value: 'AS' },
  { label: 'Sao tomé et principe', value: 'ST' },
  { label: 'Sénégal', value: 'SN' },
  { label: 'Serbie', value: 'RS' },
  { label: 'Seychelles', value: 'SC' },
  { label: 'Sierra leone', value: 'SL' },
  { label: 'Singapour', value: 'SG' },
  { label: 'Slovaquie', value: 'SK' },
  { label: 'Slovénie', value: 'SI' },
  { label: 'Somalie', value: 'SO' },
  { label: 'Soudan', value: 'SD' },
  { label: 'Soudan du sud', value: 'SS' },
  { label: 'Sri lanka', value: 'LK' },
  { label: 'Suède', value: 'SE' },
  { label: 'Suisse', value: 'CH' },
  { label: 'Suriname', value: 'SR' },
  { label: 'Svalbard et île jan mayen', value: 'SJ' },
  { label: 'Swaziland', value: 'SZ' },
  { label: 'Syrienne, république arabe', value: 'SY' },
  { label: 'Tadjikistan', value: 'TJ' },
  { label: 'Taïwan, province de chine', value: 'TW' },
  { label: 'Tanzanie, république unie de', value: 'TZ' },
  { label: 'Tchad', value: 'TD' },
  { label: 'Tchèque, république', value: 'CZ' },
  { label: 'Terres australes françaises', value: 'TF' },
  { label: 'Thaïlande', value: 'TH' },
  { label: 'Timor leste', value: 'TL' },
  { label: 'Togo', value: 'TG' },
  { label: 'Tokelau', value: 'TK' },
  { label: 'Tonga', value: 'TO' },
  { label: 'Trinité et tobago', value: 'TT' },
  { label: 'Tunisie', value: 'TN' },
  { label: 'Turkménistan', value: 'TM' },
  { label: 'Turks et caïcos, îles', value: 'TC' },
  { label: 'Turquie', value: 'TR' },
  { label: 'Tuvalu', value: 'TV' },
  { label: 'Ukraine', value: 'UA' },
  { label: 'Uruguay', value: 'UY' },
  { label: 'Vanuatu', value: 'VU' },
  { label: 'Venezuela, république bolivarienne du', value: 'VE' },
  { label: 'Viet nam', value: 'VN' },
  { label: 'Wallis et futuna', value: 'WF' },
  { label: 'Yémen', value: 'YE' },
  { label: 'Zambie', value: 'ZM' },
  { label: 'Zimbabwe​​​​​', value: 'ZW' },
];

export const countriesValues = countries.map((country) => country.value);

export default countries;
